[profile.default]
src = 'contracts'
out = 'out'
libs = ['node_modules', 'lib']
test = 'test/foundry'
cache_path  = 'forge-cache'

[fuzz]
runs = 10000
# See more config options https://book.getfoundry.sh/reference/config.html
